# 数据源配置
# hikari数据源配置
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    # 主库数据源
    master:
      jdbc-url: jdbc:mysql://localhost:3306/newbee_mall_db?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      username: root
      password:
      pool-name: hikariCP
      minimum-idle: 5
      maximum-pool-size: 10
      auto-commit: true
      idle-timeout: 10000
      max-lifetime: 30000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 1000
      password:
      client-type: lettuce
      lettuce:
        pool:
          enabled: true
      jedis:
        pool:
          max-active: 5
          max-idle: 10
          min-idle: 10
          max-wait: 3000

  # 配置rabbitMq 服务器
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    # 消息确认配置项
    # 确认消息已发送到交换机(Exchange)
    publisher-confirm-type: correlated
    # 确认消息已发送到队列(Queue)
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 100
